### ISSUE TITLE
TiM crash

### ISSUE THREAD

**Issue by ccgfok** [EternalBlueFlame/Trains-In-Motion#15]
When sitting to passenger cart, pressing L key to toggle dynamic light will crash the game.
Crash log: http://pastebin.com/zYks6V1R

**Comment by NitroxydeX** [comment]
This happens here: https://github.com/EternalBlueFlame/Trains-In-Motion/blob/master/src/main/java/trains/utility/EventManager.java#L47 because it just checks for the main entity "GenericRailTransport" which could be a passenger cart too. A check against "EntityTrainCore" should fix this problem because you cannot cast the RollingStock to the TrainCore. The check for TrainCore needs to be seperated if there is an inventory in a not train. 
https://github.com/EternalBlueFlame/Trains-In-Motion/blob/master/src/main/java/trains/utility/EventManager.java#L57 should also be checked against TrainCore not the main class.

**Comment by EternalBlueFlame** [comment]
Rollingstock are supposed to have support for lights too, the issue is actually caused from an invalid cast on line 51.
[https://github.com/EternalBlueFlame/Trains-In-Motion/blob/master/src/main/java/trains/utility/EventManager.java#L51](https://github.com/EternalBlueFlame/Trains-In-Motion/blob/master/src/main/java/trains/utility/EventManager.java#L51)

A also need to make compensations on line 58 for it it's a train to prevent ANOTHER crash there...

Overall though you were on the right track @NitroxydeX that saves me a lot of time, thanks.
