### ISSUE TITLE
[Trains In Motion Alpha 2] Cannot place any carts

### ISSUE THREAD

**Issue by ccgfok** [EternalBlueFlame/Trains-In-Motion#16]
Because placing any carts will crash the game.
Crash log: http://pastebin.com/ygU7CwRB

**Comment by EternalBlueFlame** [comment]
Thanks for the report.
I'll release a hotfix of alpha 2 later today to fix this, the issue seems to have been caused due to the motion velocity of particle effects, which is calculated based on the velocity of the bogies (because the train itself does not have velocity, which changes in alpha 3). And the bogies are not always instanced yet (in some setups the first render tick actually happens before the first entity tick).

I'll double check into this and see if there are any similar/related issues that i can patch before i release the hotfix.
