### ISSUE TITLE
Train and stock sink in into ground when placed on mincraft vanilla track

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Trains-In-Motion#18]
I don't know if this is a bug or because its still alfa and the wheels do not ride on rail surface yet . I just saw that you have released this and gave it a try . Could you add  pictures of how the train and stock should look please . I don't know if its me or just the mod is just not ready to test yet . I don't see any textures and everything disappears depending on the angel I'm viewing the train from .
![2017-03-25_02 36 35](https://cloud.githubusercontent.com/assets/22108822/24320103/ba164d84-1104-11e7-9f5b-182e72152a48.png)
![2017-03-25_02 40 58](https://cloud.githubusercontent.com/assets/22108822/24320102/ba14a394-1104-11e7-9c4d-99604fa6e687.png)

**Comment by EternalBlueFlame** [comment]
This issue is caused from my hackjob on vanilla pathfinding. In one of the upcoming updates (which i start work on today) I will be removing all traces of vanilla pathfinding and the old method for bogies, and replacing them with a more static method of pathfinding tailored to the actual nature of linear movement, to fix this issue and a number of other issues that spawn from vanilla pathfinding (like derailing).

Now as for the textures, they just aren't there yet, like the files actually do not exist except for the one sinjin made. That is how they are supposed to look at the current moment (the textures will be added in time, but for the moment, code takes priority).

Now if you notice on the log car and the well car, their bogies are in the center rather than the ends, now that is a glitch I was not aware of, thanks for (unintentionally) bringing that to my attention, i'll get that fixed asap.

**Comment by EternalBlueFlame** [comment]
i forgot to close this issue. this is fully fixed in alpha 2.5.
