### ISSUE TITLE
[2.5-alpha] Open world that have TiM 2.0.1 alpha will crash game.

### ISSUE THREAD

**Issue by ccgfok** [EternalBlueFlame/Trains-In-Motion#19]
This was happen when I updated TiM 2.0.1 alpha to 2.0.5-alpha, and when I open world that have TiM 2.0.1 alpha will crash game completely.
Crash log: https://pastebin.com/9uKZz8Kn

**Comment by EternalBlueFlame** [comment]
According to this crash log you were blocked by a firewall from connecting due to an unsafe connection.
On the main menu to boot, before any TiM resources are even touched.

You may want to try playing on an internet connection your system views as secure, like your home internet.

Or alternatively, You may want to double check your security settings.
If you're a windows user I'd recommend you start looking in your antivirus firewall settings alongside your outgoing and incoming firewall rules from the Firewall with Advanced Security menu.
If you're a linux user I'd recommend you check security settings for your shell.

Usually the blocked program would be listed as either java or minecraft.

I'm pretty sure this isn't a TiM issue, but I have seen stranger things. Let me know if you get any different results on this error.
